/*
Description: This program performs a card game called Elevens.
Programmed by: Tolentino, Hephzi-Bah G.     S18B
Last modified: November 27, 2023
Version: 1
[Acknowledgements: 
    > Fisher-Yates Algorithm - https://youtu.be/tLxBwSL3lPQ?si=NbfVO7xdpiewkM36
    > Shuffling an array - https://www.youtube.com/watch?v=7OIZ_W75lAM&pp=ygUdaG93IHRvIHNodWZmbGUgYW5kIGFycmF3IGluIGM%3D
    > time.h and srand() function - https://youtu.be/ZaZxHzRn-AY]
*/

#include <stdio.h>
#include <stdlib.h> //to use srand() and rand()
#include <time.h> //to use srand() and generate different random numbers each run

#define DECK 52
#define TABLE 9
#define INVALID "INVALID SELECTION"
#define WRONG "WRONG CARDS"
#define CELL "WRONG CELL"
#define NOTROYAL "NOT ROYAL CARDS"
#define NOT11 "NOT ELEVENS"

/*
This function generates the place in the table
Precondiiton:       card and adder non-negative numbers
                    card can be numbers from 1 to 52 (and 0)
                    adder can be numbers for 1 to 9
@param  card        the card number based on the representation given
@param  adder       multiplied by 100, the number being added to the card number to set its position 
                    (e.g., 1st cell - 100, 2nd cell - 200, etc.)
@return             returns a 3-digit number 
                    the hundreds place being the table position
                    the tens and ones are the card number
*/
int generatePlaceTable (int card, int adder)
{
    int place = card + adder * 100;

    return place;
}

/*
This function extracts the place in the table (ex. 135 - 1); 
This function will be used in getting the cards the player selected
Precondiiton:           3-digit non-zero and non-negative numbers
@param  placetable      the card number based on the representation given added with the cell number;
                        the number generated by generatePlaceTable()
@return                 returns the hundreds digit which defines the place in the table
*/
int extractPlaceTable (int placetable)
{
    int extract = placetable / 100;

    return extract;
}

/*
This function extracts the card number (ex. 135 - 35)
Precondiiton:           3-digit non-zero and non-negative numbers
@param  placetable      the card number based on the representation given added with the cell number
                        the number generated by generatePlaceTable()
@return                 returns the 2 rightmost digits (ones and tens) which defines the card number
*/
int extractCardNumber (int placetable)
{
    int extract = placetable % 100;

    return extract;
}

/*
This function checks if the card is a Jack
Precondiiton:       accepts integers from 1 to 52 (and 0)
@param  card        the card number based on the representation given
@return             returns 1 if Jack, returns 0 if not
*/
int isCardJack (int card)
{
    int res = 0;

    if (card % 13 == 11)
        res = 1;
    
    return res;
}

/*
This function checks if the card is a Queen
Precondiiton:       accepts integers from 1 to 52 (and 0)
@param  card        the card number based on the representation given
@return             returns 1 if Queen, returns 0 if not
*/
int isCardQueen (int card)
{
    int res = 0;

    if (card % 13 == 12)
        res = 1;
    
    return res;
}

/*
This function checks if the card is a King
Precondiiton:       accepts integers from 1 to 52 (and 0)
@param  card        the card number based on the representation given
@return             returns 1 if King, returns 0 if not
*/
int isCardKing (int card)
{
    int res = 0;

    if (card % 13 == 0 && card != 0)
        res = 1;

    return res;
}

/*
This function identifies the card suit based on the number generated
Precondiiton:       integers from 1 to 52 (and 0)
                    code (card suit) is set to null character by default
@param  card        the card number based on the representation given
@param  *code       stores the char code for suit
                    char 'D' (Diamond), 'C' (Club), 'H' (Heart), or 'S' (Spade)
*/
void identifyCardSuit (int card, char* code) 
{
	*code = '\0';

    if (card == 0)
        *code = ' ';
    else if (card <= 13)
        *code = 'D';
    else if (card <= 26)
        *code = 'C';
    else if (card <= 39)
        *code = 'H';
    else if (card <= 52)
        *code = 'S';
}

/*
This function identifies card rank (A-10) or royal (J/Q/K)
Precondiiton:           integers from 1 to 52 (and 0)
@param  card            the card number based on the representation given
@param  *cardrank1      stores the char code for the first character
                        except for cases that require two digits (10 = '1' and '0'), the ' ' (space) is for alignment purposes
@param  *cardrank2      stores the char code for the second character
                        it can be A, K, Q, J, 0, and 2 to 9
*/
void identifyCardRank (int card, char* cardrank1, char* cardrank2)
{
    if (card == 0)
    {
        *cardrank1 = ' ';
        *cardrank2 = ' ';
    }
    else if ((card - 1) % 13 == 0)
	{
        *cardrank1 = ' ';
		*cardrank2 = 65; //65 = A
	}
	else if (isCardKing (card))
    {
        *cardrank1 = ' ';
        *cardrank2 = 75; //75 = K
    }
    else if (isCardQueen (card))
    {
        *cardrank1 = ' ';
        *cardrank2 = 81; //81 = Q
    }
    else if (isCardJack (card))
    {
        *cardrank1 = ' ';
        *cardrank2 = 74; //74 = J
    }
    else if (card % 13 > 1 && card % 13 < 10)
    {
        *cardrank1 = ' ';
        *cardrank2 = card % 13 + 48; //numbers 2 to 9
    }
    else 
    {
        *cardrank1 = 49; //1
        *cardrank2 = 48; //0
    }
}

/*
This function identifies the color of the card (red/black) and is used for scoring
Precondiiton:       integers from 1 to 52; cards that have been validated by is2Cards11() and is3CardsRoyal()
                    calls the function identifyCardSuit()
@param  card        the card number based on the representation given
@param  *color      stores the values 1 and 0 
                    (1 if red, 0 if black)
*/
void identifyCardColor (int card, int* color)
{
    char suit;
    identifyCardSuit (card, &suit);

    switch (suit)
    {
        case 'D':
            *color = 1;
            break;
        case 'C':
            *color = 0;
            break;
        case 'H':
            *color = 1;
            break;
        case 'S':
            *color = 0;
            break;
    }
}

/*
This function verifies if 2 cards are equal to 11
Precondiiton:       accepts integers from 1 to 52
                    -- edit: integers 1-52 except numbers that represent royal cards
@param  card1       first card representation of user input 
@param  card2       second card representation of user input
@return             returns 1 if 2 cards sums up to 11, returns 0 if not
*/
int is2Cards11 (int card1, int card2)
{
    int res = 0;

    if ((card1 + card2) % 13 == 11)
        res = 1;

    return res;
}

//BONUS FEATURE: Skipping all royal card when game mode 2 is chosen
/*This function identifies if the card is a royal
Precondiiton:       calls isCardJack(), isCardQueen(), and isCardKing()
@param  card        card number based on the representation given
@return             returns 1 if card is a royal (either Jack, Queen, or King)
*/
int isRoyalCard (int card)
{
	int res = 0;
	
    if (isCardJack (card) || isCardQueen (card) || isCardKing (card))
		res = 1;
	
	return res;
}

/*
This function verifies if 3 cards are all royalty
Precondiiton:       accepts integers from 1 to 52
                    -- edit: integers 1-52 that have been validated by isRoyalCard()
@param  card1       first card representation of user input 
@param  card2       second card representation of user input
@param  card3       third card representation of user input
@return             returns 1 if 3 cards are a set of Royals, 0 if not
*/
int is3CardsRoyal (int card1, int card2, int card3)
{
    int res = 0;
   
    if ((card1 % 13 + card2 % 13 + card3 % 13) % 13 == 10)
        res = 1;

    return res;
}

/*
This function gives scores based on the given conditions
Precondiiton:       cards that have been validated by is2Cards11
                    calls identifyCardSuit() and identifyCardColor()
@param  card1       first card representation of user input 
@param  card2       second card representation of user input
@return             returns 3 if same suit, 2 if same color, 1 by default
*/
int getScore11 (int card1, int card2)
{
    char suit1, suit2;
    int color1, color2;
    int score = 1;

    identifyCardSuit (card1, &suit1);
    identifyCardSuit (card2, &suit2);
    identifyCardColor (card1, &color1);
    identifyCardColor (card2, &color2);

    if (suit1 == suit2)
        score = 3;
    else if (color1 == color2)
        score = 2;

    return score;
}

/*
This function gives scores based on the given conditions
Precondiiton:       cards that have been validated by is3CardsRoyal
                    calls identifyCardSuit() and identifyCardColor()
@param  card1       first card representation of user input 
@param  card2       second card representation of user input
@param  card3       third card representation of user input
@return             returns 3 if same suit, 2 if same color, 1 by default
*/
int getScoreRoyal (int card1, int card2, int card3)
{
    char suit1, suit2, suit3;
    int color1, color2, color3;
    int score = 1;

    identifyCardSuit (card1, &suit1);
    identifyCardSuit (card2, &suit2);
    identifyCardSuit (card3, &suit3);
    identifyCardColor (card1, &color1);
    identifyCardColor (card2, &color2);
    identifyCardColor (card3, &color3);

    if (suit1 == suit2 && suit1 == suit3 && suit2 == suit3)
        score = 3;
    else if (color1 == color2 && color1 == color3 && color2 == color3)
        score = 2;

    return score;
}

/*
This function checks if Jack, Queen, King are present in a table
Precondiiton:       accepts integers 1 or 0
@param  jack        result of isCardJack
@param  queen       result of isCardQueen
@param  king        result of isCardKing
@return             returns 1 if a set of royal cards is present, returns 0 if not
*/
int areRoyalsPresent (int jack, int queen, int king)
{
    int res = 0;

    if (jack == 1 && queen == 1 && king == 1)
        res = 1;

    return res;
}

/*
This function prints a row of card
Precondiiton:               card codes and suits are results of identifyCardRank() & identifyCardSuit()
@param  card1_code1        	results of identifyCardRank() for the 1st card
@param	card1_code2        	results of identifyCardRank() for the 1st card
@param  card2_code1       	results of identifyCardRank() for the 2nd card
@param  card2_code2			results of identifyCardRank() for the 2nd card
@param  card3_code1       	results of identifyCardRank() for the 3rd card 
@param  card3_code2			results of identifyCardRank() for the 3rd card 
@param  suit1               result of identifyCardSuit() for 1st card
@param  suit2               result of identifyCardSuit() for 2nd card
@param  suit3               result of identifyCardSuit() for 3rd card
*/
void printCardRow   (int card1_code1, int card1_code2, 
                    int card2_code1, int card2_code2,
                    int card3_code1, int card3_code2,
                    char suit1, char suit2, char suit3)
{
    int row;

    for (row = 1; row <= 11; row ++)
    {
        if (row == 1 || row == 11)
            printf  ("\t     | - - - - - - - - - || - - - - - - - - - || - - - - - - - - - |\n");
        else if (row == 2)
            printf  ("\t     |   %c%c              ||   %c%c              ||   %c%c              |\n",
                    card1_code1, card1_code2, card2_code1, card2_code2, card3_code1, card3_code2);
        else if (row == 6)
            printf  ("\t     |         %c         ||         %c         ||         %c         |\n",
                    suit1, suit2, suit3);
        else if (row == 10)
            printf  ("\t     |              %c%c   ||              %c%c   ||              %c%c   |\n",
                    card1_code1, card1_code2, card2_code1, card2_code2, card3_code1, card3_code2);
        else 
            printf ("\t     |                   ||                   ||                   |\n");
    }
}

/*
This function allows user selection in the menu
@return     user selection for menu
*/
char chooseMenu ()
{
    char selection;

    printf ("\nEnter selection: ");
    scanf (" %c", &selection);

    return selection;
}

/*
This function allows user selection in the settings
@return     user selection for setting
*/
char chooseSettings ()
{
    char selection;

    printf ("\nEnter selection: ");
    scanf (" %c", &selection);

    return selection;
}

/*
This function allows user to change player mode and also displays if user input is valid or not
Precondiiton:       accepts any number but verifies it as well
                    default player mode is 1 PLAYER
@param  *pMode      a pointer to PlayerMode which defines the number of players as set by the user
*/
void choosePlayerMode (int* pMode)
{
    int tempMode = *pMode;

    printf ("\n<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>\n");
    printf ("\n                   ~~ PLAYER MODES ~~\n");
    printf ("\n             ~~ CURRENT MODE: %d PLAYER ~~\n\n", tempMode);

    printf ("              1 PLAYER     |     2 PLAYER\n");
    printf ("                 [1]       |        [2]\n\n");
 
    printf ("Choose mode [1 or 2]: ");
    scanf ("%d", &tempMode);

    switch (tempMode)
    {
        case 1:
            printf ("\nYour player mode is set to 1 PLAYER.\n");
            break;
        case 2:
            printf ("\nYour player mode is set to 2 PLAYERS.\n");
            break;
        default:
        {
            printf ("\n%s -- You are set back to default (1 player)\n", INVALID);
            tempMode = 1; //Go back to default
        }
            break;
    }

    *pMode = tempMode;
}

/*
This function allows user to change game mode and also displays if user input is valid or not
Precondiiton:       accepts any number but verifies it as well
                    default player mode is 1 (COMPLETE DECK)
@param  *pMode      a pointer to GameMode which defines the game mode as set by the user
*/
void chooseGameMode (int* gMode)
{
	int tempMode = *gMode;
	
	printf ("\n<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>\n");
    printf ("\n                   ~~ GAME MODES ~~\n");
    printf ("\n                ~~ CURRENT MODE: %d ~~\n\n", tempMode);

    printf ("        COMPLETE DECK     |       RANK CARDS \n");
    printf ("             [1]          |           [2]\n\n");
    
    printf ("Choose mode [1 or 2]: ");
    scanf ("%d", &tempMode);
    
    switch (tempMode)
    {
        case 1:
            printf ("\nYour game mode is set to COMPLETE DECK.\n");
            break;
        case 2:
            printf ("\nYour game mode is set to RANK CARDS.\n");
            break;
        default:
        {
            printf ("\n%s -- You are set back to default (COMPLETE DECK)\n", INVALID);
            tempMode = 1; //Go back to default
        }
            break;
    }
    
    *gMode = tempMode;
}

/*
This function displays the menu
*/
void displayWelcomeAndMenu ()
{
    printf ("\n");
    printf ("<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<");

    printf ("\n\n");

    printf ("                            ! ! W  E  L  C  O  M  E ! !");
    printf ("\n\n");
    printf ("                                    ~~ T  O ~~");
    printf ("\n\n");

    printf ("    = = = =    =       = = = =     =         =     = = = =     = =     =     = = = =\n");
    printf ("    =          =       =           =         =     =           =  =    =     =\n");
    printf ("    = = =      =       = = =        =       =      = = =       =   =   =       = =\n");
    printf ("    =          =       =             =     =       =           =    =  =           =\n");
    printf ("    = = = =    = = =   = = = =         = =         = = = =     =     = =     = = = =\n");

    printf ("\n");

    printf ("<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<");

    printf ("\n\n");

    printf ("\t\t\t           > NEW GAME [N] \t\n");
    printf ("\t\t\t           > SETTINGS [S] \t\n");
    printf ("\t\t\t           > EXIT     [E] \t\n");
}

/*
This function displays the settings and asks for user selection by calling the function chooseSettings()
@param  *pSetting       a pointer to SettingSelection which stores user setting selection
*/
void displaySettings (char* pSetting)
{   
    printf ("\n<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>");
    printf ("\n\n         ~~ You are currently in SETTINGS ~~ \n\n");

    printf ("> Player Mode [P]\n");
    printf ("> Game Mode [G]\n");
    printf ("> Back to Main Menu [B]\n");

    *pSetting = chooseSettings ();
}

/*
This function displays "NEW GAME" 
Precondiiton:           accepts 1 or 2
@param  playmode        the player mode as selected by user
                        result of choosePlayerMode
@param  gamemode        the game mode as selected by user
                        result of chooseGameMode
*/
void displayNewGame (int playmode, int gamemode)
{
    printf ("\n<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:< ");
    printf ("\n\n\t                       ~~ You started a NEW GAME ~~ \n\n");

    if (playmode == 1)
        printf ("\t                             [1 PLAYER MODE]\n");
    else  
        printf ("\t                             [2 PLAYER MODE]\n");

    if (gamemode == 1)
        printf ("\t                           [COMPLETE DECK MODE]\n");
    else
        printf ("\t                            [RANK CARD MODE]\n");
}

/*
This function prints instructions and mechanics
*/
void displayInstrucAndMech (int gamemode, int playmode)
{
    char enter;
    int row, num = 1;

    printf ("\n<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<\n\n");

    printf ("                                 ~~ GAME MECHANICS ~~\n\n");
    printf ("> Eliminating number cards:\n");
    printf ("\t> Select two cards that sums up to 11 regardless of suit.\n");
    printf ("\t  Example: Ace of Hearts and 10 of Clubs.\n\n");

    if (gamemode == 1)
    {
        printf ("> Eliminating royal cards:\n");
        printf ("\t> To eliminate royal cards, a set of Jack, Queen, and King must be selected.\n\n");
    }

    if (playmode == 1)
        printf ("> The game ends when there are no cards that can be eliminated.\n\n");
    else
    {
        printf ("> Players take turns in eliminating cards.\n\n");
        printf ("> Scoring:\n");
        printf ("\t> Eliminating cards gives 1 point.\n");
        printf ("\t> Eliminating cards with same suit gives 3 points.\n");
        printf ("\t> Eliminating cards with same color gives 2 points.\n\n");
        printf ("> The game ends when there are no cards that can be eliminated.\n\n");
    }
    
    printf ("Type any letter for instructions -- ");
    scanf (" %c", &enter);
    
    printf ("\n<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<:>:<\n\n");

    printf ("                                 ~~ INSTRUCTIONS ~~\n\n");
    printf ("> You will be presented with nine cards.\n\n");

    //Printing cell guide
    for (row = 1; row <= 13; row++)
    {
        if (row == 1 || row == 5 || row == 9 || row == 13)
            printf ("\t\t| - - - | - - - | - - - |\n");
        else if (row == 3 || row == 7 || row == 11)
        {   
            printf("\t\t|   %d   |   %d   |   %d   |\n", num, num + 1, num + 2);
            num+=3;
        }
        else 
            printf("\t\t|       |       |       |\n");
    }

    printf ("\n");
    
    printf ("> Each cell is numbered from 1 to 9.\n\n");
    printf ("> The letters at the middle are the code for suits.\n\n");
    printf ("\tS = Spades | C = Clubs | D = Diamonds | H = Hearts\n\n");

    if (gamemode == 1)
        printf ("> You will be asked if you are to eliminate number cards or royal cards.\n\n");

    printf ("> Type the number of the cell of your chosen card.\n\n");
    printf ("> If you wish to end the game, enter [0] during first card selection.\n\n");

    printf ("Type any letter to start -- ");
    scanf (" %c", &enter);
}

int main ()
{
    //Variables for menu and settings
    char    MenuSelection, SettingSelection;
    int     PlayerMode, GameMode;
    int     endMenuLoop, endSettingsLoop; //Loop tracking

    srand (time(NULL)); //Generating random numbers using the time seed
    //Variables for generating card
    int     counter, index, temp, RandIndex, tableLabel, repIndex, CardVal;
    int     Cards[DECK];
    int     TableCards[TABLE];
    char    CardSuit[TABLE], CardCode1[TABLE], CardCode2[TABLE];

    //Variables for the game
    int     scoreP1, scoreP2, currentPlayer;
    int     endSelectLoop, endRNSelectLoop, endCardLoop, endGameLoop; //Loop tracking
    char    RCardNCard; //Royal card or Number card
    int     CardSelect1, CardSelect2, CardSelect3; //User card selection
    int     Card1, Card2, Card3; //Converted card representation of user input
    int     cards11, cardsRoyal; //Verifies if 2 cards are equal to 11; 3 cards are all royals

    //Variables for checking table 
    int     playValid11, playValidR;
    int     index1, index2;
    int     JackCheck, QueenCheck, KingCheck;   

    endGameLoop = 0;
    while (endGameLoop == 0) //S-GameLoop
    {
        // ----------------------- MENU ----------------------- //

        displayWelcomeAndMenu ();

        PlayerMode = 1; //Restarts to default (1 player)
        GameMode = 1; //Restarts to default (complete deck)

        endMenuLoop = 0;
        repIndex = 0;
        while (endMenuLoop == 0) //S-MenuLoop 
        {
            MenuSelection = chooseMenu ();

            if (MenuSelection == 'S' || MenuSelection == 's')
            {
                endSettingsLoop = 0;
                while (endSettingsLoop == 0) //S-SettingsLoop
                {
                    displaySettings (&SettingSelection);
                    if (SettingSelection == 'P' || SettingSelection == 'p')
                        choosePlayerMode (&PlayerMode);
                    else if (SettingSelection == 'G' || SettingSelection == 'g')
                    	chooseGameMode (&GameMode);
                    else if (SettingSelection == 'B' || SettingSelection == 'b')
                    {
                        endSettingsLoop = 1;
                        displayWelcomeAndMenu();
                    }
                    else
                        printf ("\n%s\n", INVALID);
                } //E-SettingsLoop
            }
            else if (MenuSelection == 'N' || MenuSelection == 'n' || MenuSelection == 'E' || MenuSelection == 'e')
                endMenuLoop = 1;
            else
                printf ("\n%s\n", INVALID);
        } //E-MenuLoop

        // ----------------------- GAME ----------------------- //

        if (MenuSelection == 'N' || MenuSelection == 'n')
        { //DON'T EDIT OUTSIDE THIS BRACKET
        
            displayInstrucAndMech (GameMode, PlayerMode);
            displayNewGame (PlayerMode, GameMode);

            // ---------- INITIALIZE ----------- //
            
            scoreP1 = 0; scoreP2 = 0; currentPlayer = 1;

            //Filling the card array
            CardVal = 1;
            for (index = 0; index < DECK; index++) //1
                Cards[index] = CardVal++; //2
            //Fisher-Yates Algorithm
            for (index = 52 - 1; index >= 0; index--)
            {
                RandIndex = rand () % (index + 1);
                
                temp = Cards[index];
                Cards[index] = Cards[RandIndex];
                Cards[RandIndex] = temp;
            }
            //Setting the first 9 cards
            index = 0;
            for (counter = 1; counter <= TABLE; counter++)
            {
                TableCards[index] = Cards[index];
                Cards[index] = 0;

                //BONUS FEATURE: Skipping all royal card when game mode 2 is chosen
                if (GameMode == 2)
                {
                    while (isRoyalCard (TableCards[index]))
                    {
                        TableCards[index] = Cards[--repIndex];
                        Cards[repIndex] = 0;
                    }
                }
                
                TableCards[index] = generatePlaceTable (TableCards[index], counter);

                identifyCardSuit (extractCardNumber (TableCards[index]), &CardSuit[index]);
                identifyCardRank (extractCardNumber (TableCards[index]), &CardCode1[index], &CardCode2[index]);
                
                index++;
            }
            
            // ---------- START OF 1 RUN ----------- //

            endCardLoop = 0; 
            while (endCardLoop == 0) //S-CardLoop
            {
                //Printing card table
                tableLabel = 1;
                for (index = 0; index < 3; index++)
                {
                    printf ("\n\n\t               %d          ", tableLabel++);
                    printf ("          %d          ", tableLabel++);
                    printf ("          %d         \n", tableLabel++);
                    printCardRow    (CardCode1 [0 + 3 * index], CardCode2 [0 + 3 * index],
                                    CardCode1 [1 + 3 * index], CardCode2 [1 + 3 * index], 
                                    CardCode1 [2 + 3 * index], CardCode2 [2 + 3 * index], 
                                    CardSuit [0 + 3 * index], CardSuit [1 + 3 * index], 
                                    CardSuit [2 + 3 * index]);

                    printf ("\n");
                }
                //Status of player/s
                switch (PlayerMode) //S-PlayerMode
                { 
                    case 1:
                        printf("\n                                       >> PLAYER 1\n");
                        break;
                    case 2:
                        if (currentPlayer % 2 != 0)
                        {
                            printf("\n                      >> PLAYER 1                       SCORE: %d\n", scoreP1);
                            printf("                         PLAYER 2                       SCORE: %d\n", scoreP2);
                        }
                        else if (currentPlayer % 2 == 0)
                        {
                            printf("\n                         PLAYER 1                       SCORE: %d\n", scoreP1);
                            printf("                      >> PLAYER 2                       SCORE: %d\n", scoreP2);
                        }
                        break;
                } //E-PLayerMode

                // ---------- CHECKING IF TABLE IS STILL PLAYABLE ----------- //

                playValid11 = 0; playValidR = 0; //Restarts to 0 every loop
                JackCheck = 0; QueenCheck = 0; KingCheck = 0; //Restarts to 0 every loop     

                //Check if cards are still playable (equal 11)
                index1 = 0; 
                while (index1 < TABLE) 
                {
                    index2 = 0;
                    if (!isRoyalCard (extractCardNumber (TableCards[index1])))
                    {
                        while (index2 < TABLE)
                        {   
                            if  (extractCardNumber (TableCards[index2]) != extractCardNumber (TableCards[index1]))
                            {
                                playValid11 = is2Cards11    (extractCardNumber (TableCards[index1]), 
                                                            extractCardNumber (TableCards[index2]));
                            }

                            if (playValid11 == 0)
                                index2++;
                            else
                                index2 = 9;
                        }
                    }

                    if (playValid11 == 0)
                        index1++;
                    else 
                        index1 = 9;
                }
                //Check if cards are still playable (3 royalties)
                for (index = 0; index < TABLE; index++)
                {
                    JackCheck = isCardJack (extractCardNumber (TableCards[index]));

                    if (JackCheck == 1)
                        index = 9;
                }
                for (index = 0; index < TABLE; index++)
                {
                    QueenCheck = isCardQueen (extractCardNumber (TableCards[index]));

                    if (QueenCheck == 1)
                        index = 9;
                }
                for (index = 0; index < TABLE; index++)
                {
                    KingCheck = isCardKing (extractCardNumber (TableCards[index]));

                    if (KingCheck == 1)
                        index = 9;
                }
                playValidR = areRoyalsPresent (JackCheck, QueenCheck, KingCheck);

                endSelectLoop = 1; //Sets whether selection part starts or not
                if (playValid11 == 1 || playValidR == 1)
                    endSelectLoop = 0;
                else 
                {
                    if (PlayerMode == 2)
                    {
                        if (scoreP1 > scoreP2)
                            printf("\n                                  PLAYER 1 is the WINNER!\n");
                        else if (scoreP2 > scoreP1)
                            printf("\n                                  PLAYER 2 is the WINNER!\n");
                        else
                            printf("\n                                           TIE\n");
                    }
                    else if (PlayerMode == 1 && repIndex == 0)
                        printf ("\n                                CONGRATULATIONS! YOU WON!\n");
                    else
                        printf("\n                                        GAME OVER\n");
                    
                    endCardLoop = 1;
                }

                // ---------- SELECTION ----------- //

                CardSelect1 = 0; CardSelect2 = 0; CardSelect3 = 0; 
                Card1 = 0; Card2 = 0; Card3 = 0;

                while (endSelectLoop == 0)
                {
                    endRNSelectLoop = 0;
                    RCardNCard = 'N';

                    if (GameMode == 1)
                    {
                        while (endRNSelectLoop == 0)
                        {
                            printf ("\n");
                            printf ("\t\t\t          ROYAL CARD or NUM CARD\n");
                            printf ("\t\t\t             [R]          [N]\n");

                            printf ("\nEnter selection [R or N]: ");
                            scanf (" %c", &RCardNCard);

                            if (RCardNCard != 'R' && RCardNCard != 'r' && RCardNCard != 'N' && RCardNCard != 'n')
                                printf("\n%s\n", INVALID);
                            else
                                endRNSelectLoop = 1;
                        }//E-FCSelectLoop
                    }

                    printf ("\n"); //Spacer

                    do 
                    {
                        CardSelect1 = 0; //Restarts every loop
                        printf ("Enter 1st Card [1 - 9]: ");
                        scanf ("%d", &CardSelect1);

                        if (!(CardSelect1 > -1 && CardSelect1 < 10))
                            printf ("\n%s\n\n", CELL);
                        else if (CardSelect1 == 0)
                            printf ("\nBACK TO MENU\n");
                    } while (!(CardSelect1 > -1 && CardSelect1 < 10));

                    if (CardSelect1 != 0)
                    {
                        do 
                        {
                            CardSelect2 = 0; //Restarts every loop
                            printf ("Enter 2nd Card [1 - 9]: ");
                            scanf ("%d", &CardSelect2);

                            if (!(CardSelect2 > 0 && CardSelect2 < 10))
                                printf("\n%s\n\n", CELL);
                        } while (!(CardSelect2 > 0 && CardSelect2 < 10));

                        if (RCardNCard == 'R' || RCardNCard == 'r')
                        {
                            do 
                            {
                                CardSelect3 = 0; //Restarts every loop
                                printf ("Enter 3rd Card [1 - 9]: ");
                                scanf ("%d", &CardSelect3);

                                if (!(CardSelect3 > 0 && CardSelect3 < 10))
                                    printf("\n%s\n\n", CELL);
                            } while (!(CardSelect3 > 0 && CardSelect3 < 10));
                        }

                        // ------- MATCHING THE 2 / 3 CARDS -------- //

                        for (index = 0; index < TABLE; index++)
                        {
                            if (CardSelect1 == extractPlaceTable (TableCards[index]))
                            {
                                Card1 = extractCardNumber (TableCards[index]);
                                index = 9;
                            }
                        }
                        for (index = 0; index < TABLE; index++)
                        { 
                            if (CardSelect2 == extractPlaceTable (TableCards[index]))
                            {
                                Card2 = extractCardNumber (TableCards[index]);
                                index = 9;
                            }
                        }

                        cards11 = 0; cardsRoyal = 0; //Restarts to 0 every loop

                        if (RCardNCard == 'R' || RCardNCard == 'r')
                        {
                            for (index = 0; index < TABLE; index++)
                            { 
                                if (CardSelect3 == extractPlaceTable (TableCards[index]))
                                {
                                    Card3 = extractCardNumber (TableCards[index]);
                                    index = 9;
                                }
                            }
                            
                            if (Card1 == 0 || Card2 == 0 || Card3 == 0)
                                printf("\nEMPTY CELL SELECTED\n");
                            else if (!(isRoyalCard (Card1) && isRoyalCard (Card2) && isRoyalCard (Card3)))
                                printf("\nSELECT ONLY ROYAL CARDS\n");
                            else if (Card1 == Card2 || Card1 == Card3 || Card2 == Card3)
                                printf("\nSELECT DISTINCT CARDS\n");
                            else
                                cardsRoyal = is3CardsRoyal (Card1, Card2, Card3);

                            if (cardsRoyal == 0) 
                            printf("\n%s -- %s\n", WRONG, NOTROYAL);

                            if (cardsRoyal == 1 && currentPlayer % 2 != 0)
                                scoreP1 += getScoreRoyal (Card1, Card2, Card3);
                            else if (cardsRoyal == 1 && currentPlayer % 2 == 0)
                                scoreP2 += getScoreRoyal (Card1, Card2, Card3);
                        }
                        else if (RCardNCard == 'N' || RCardNCard == 'n')
                        {
                            if (Card1 == 0 || Card2 == 0)
                                printf("\nEMPTY CELL SELECTED\n");
                            else if (isRoyalCard (Card1) || isRoyalCard (Card2))
                                printf("\nSELECT ONLY NUMBER CARDS\n");
                            else if (Card1 == Card2)
                                printf("\nSELECT DISTINCT CARDS\n");
                            else
                                cards11 = is2Cards11 (Card1, Card2);

                            if (cards11 == 0) 
                                printf("\n%s -- %s\n", WRONG, NOT11);

                            if (cards11 == 1 && currentPlayer % 2 != 0)
                                scoreP1 += getScore11 (Card1, Card2);
                            else if (cards11 == 1 && currentPlayer % 2 == 0)
                                scoreP2 += getScore11 (Card1, Card2);
                        }

                        if (cards11 == 1 || cardsRoyal == 1)
                            endSelectLoop = 1;
                        else
                        {
                            currentPlayer++;
                            switch (PlayerMode) //S-PlayerMode
                            { 
                                case 1:
                                    printf("\n                                       >> PLAYER 1\n");
                                    break;
                                case 2:
                                    if (currentPlayer % 2 != 0)
                                    {
                                        printf("\n                      >> PLAYER 1                       SCORE: %d\n", scoreP1);
                                        printf("                         PLAYER 2                       SCORE: %d\n", scoreP2);
                                    }
                                    else if (currentPlayer % 2 == 0)
                                    {
                                        printf("\n                         PLAYER 1                       SCORE: %d\n", scoreP1);
                                        printf("                      >> PLAYER 2                       SCORE: %d\n", scoreP2);
                                    }
                                    break;
                            } //E-PLayerMode
                        }
                    }
                    else 
                        endSelectLoop = 1;
                }//E-SelectLoop

                if (CardSelect1 != 0)
                {
                    // -------------- REPLACING CARDS -------------- //

                    index = 0;
                    for (counter = 1; counter <= TABLE; counter++)
                    {
                        if (Card1 == extractCardNumber (TableCards[index]))
                        {
                            TableCards[index] = Cards[--repIndex];
                            Cards[repIndex] = 0;

                            //BONUS FEATURE: Skipping all royal card when game mode 2 is chosen 
                            if (GameMode == 2)
                            {
                                while (isRoyalCard (TableCards[index]))
                                {
                                    TableCards[index] = Cards[--repIndex];
                                    Cards[repIndex] = 0;
                                }
                            }

                            TableCards[index] = generatePlaceTable (TableCards[index], counter);
                        }
                        index++;
                    }

                    index = 0;
                    for (counter = 1; counter <= TABLE; counter++)
                    {
                        if (Card2 == extractCardNumber (TableCards[index]))
                        {
                            TableCards[index] = Cards[--repIndex];
                            Cards[repIndex] = 0;

                            //BONUS FEATURE: Skipping all royal card when game mode 2 is chosen 
                            if (GameMode == 2)
                            {
                                while (isRoyalCard (TableCards[index]))
                                {
                                    TableCards[index] = Cards[--repIndex];
                                    Cards[repIndex] = 0;
                                }
                            }

                            TableCards[index] = generatePlaceTable (TableCards[index], counter);
                        }
                        index++;
                    }

                    //Executes only when Royal card is chosen
                    if (RCardNCard == 'R' || RCardNCard == 'r')
                    {
                        index = 0;
                        for (counter = 1; counter <= TABLE; counter++)
                        {
                            if (Card3 == extractCardNumber (TableCards[index]))
                            {
                                TableCards[index] = Cards[--repIndex];
                                Cards[repIndex] = 0;

                                TableCards[index] = generatePlaceTable (TableCards[index], counter);
                            }
                            index++;
                        }
                    }

                    index = 0;
                    for (counter = 1; counter <= TABLE; counter++)
                    {
                        identifyCardSuit (extractCardNumber (TableCards[index]), &CardSuit[index]);
                        identifyCardRank (extractCardNumber (TableCards[index]), &CardCode1[index], &CardCode2[index]);

                        index++;
                    }

                    if (PlayerMode == 2)
                        currentPlayer++;
                }
                else
                    endCardLoop = 1;
            } //E-CardLoop; DO NOT EDIT OUTSIDE THIS BRACKET
        } //DO NOT EDIT OUTSIDE THIS BRACKET
        else
        {
            endGameLoop = 1;
            printf ("\nThank you for playing!\n");
        }             
    } //E-GameLoop

    return 0;
}